export default {
  login: 'joaogn',
  id: 10895903,
  node_id: 'MDQ6VXNlcjEwODk1OTAz',
  avatar_url: 'https://avatars.githubusercontent.com/u/10895903?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/joaogn',
  html_url: 'https://github.com/joaogn',
  followers_url: 'https://api.github.com/users/joaogn/followers',
  following_url: 'https://api.github.com/users/joaogn/following{/other_user}',
  gists_url: 'https://api.github.com/users/joaogn/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/joaogn/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/joaogn/subscriptions',
  organizations_url: 'https://api.github.com/users/joaogn/orgs',
  repos_url: 'https://api.github.com/users/joaogn/repos',
  events_url: 'https://api.github.com/users/joaogn/events{/privacy}',
  received_events_url: 'https://api.github.com/users/joaogn/received_events',
  type: 'User',
  site_admin: false,
  name: 'João Graça Neto',
  company: 'JGNdev',
  blog: 'https://www.linkedin.com/in/joaogn/',
  location: 'Salvador / Brazil',
  email: null,
  hireable: null,
  bio:
    'FullStack Developer NodeJs, React and React Native, Enthusiastic UI/UX Design',
  twitter_username: null,
  public_repos: 48,
  public_gists: 1,
  followers: 22,
  following: 30,
  created_at: '2015-02-07T11:59:50Z',
  updated_at: '2021-03-04T16:02:03Z',
};
