require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'DevMap2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'DevMap2Tests' do
    inherit! :complete
    # Pods for testing
  end

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
  post_install do |installer|
    $RNMBGL.post_install(installer)
    flipper_post_install(installer)
  end
end

target 'DevMap2-tvOS' do
  # Pods for DevMap2-tvOS

  target 'DevMap2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
